version: '3.8'

services:
  notif_db:
    container_name: notif_db
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.prod
    restart: always
  notif_worker:
    container_name: notif_worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    env_file:
      - env/.env.prod
    depends_on:
      - notif_db
      - notif_redis
    command: 'celery -A configs.celery worker -l info --autoscale=4,2'
    logging:
      driver: "json-file"
      options:
        max-file: "5" # количество файлов
        max-size: "10m" # размер файла лога
  notif_beat:
    container_name: notif_beat
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    env_file:
      - env/.env.prod
    depends_on:
      - notif_db
      - notif_redis
      - notif_worker
    command: 'celery -A configs.celery beat -l info'
  notif_redis:
    container_name: notif_redis
    image: redis
    restart: always
    expose:
      - 6379