# Generated by Django 5.1 on 2024-09-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Новость Продвижение ВБ',
                'verbose_name_plural': 'Новости Продвижение ВБ',
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Новость Медиа ВБ',
                'verbose_name_plural': 'Новости Медиа ВБ',
            },
        ),
        migrations.CreateModel(
            name='NewsSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('sent_to_telegram', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Новость Seller ВБ',
                'verbose_name_plural': 'Новости Seller ВБ',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('link', models.URLField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.TextField(verbose_name='Айди саплаера')),
                ('validation_key', models.TextField(verbose_name='Ключ валидации')),
                ('seller_device_id', models.TextField(verbose_name='Device id')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
            ],
            options={
                'verbose_name': 'Орагнизация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='OzonNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_telegram', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Новость Ozon',
                'verbose_name_plural': 'Новости Ozon',
            },
        ),
    ]
