# Generated by Django 5.1 on 2024-09-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscpm',
            name='news_id',
            field=models.IntegerField(unique=True),
        ),
    ]
