# Generated by Django 5.1 on 2024-09-24 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_newscpm_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscpm',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
