# Generated by Django 5.1 on 2024-09-24 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_newscpm_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmedia',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
